# -*- coding: utf-8 -*-
"""aicup_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ho3MWKTgUgxFLG-sHzMymZtto6guihan
"""

!pip install tsfresh PyWavelets dtaidistance

!pip install catboost

cd /content/drive/MyDrive/work/tt

from aicup_advanced_cnn import build_and_save_tsfresh
import pandas as pd

train_info = pd.read_csv('/content/drive/MyDrive/work/tt/39_Training_Dataset/train_info.csv')
build_and_save_tsfresh(
    train_info,
    '/content/drive/MyDrive/work/tt/39_Training_Dataset/train_data'
)

!python aicup_advanced_cnn.py